-optimizationpasses 10
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-dontpreverify
-optimizations *
-checkdiscard class kotlin.Metadata
-allowaccessmodification
-repackageclasses
-verbose
