-optimizationpasses 10
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-dontpreverify
-optimizations *
-checkdiscard class kotlin.Metadata
-allowaccessmodification
-repackageclasses
-verbose
-keepattributes LineNumberTable,SourceFile
-renamesourcefileattribute SourceFile
